## Creating DataFrames for Plotting

The cells below can be use as a starter template for new notebooks.

In [4]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [5]:
nfl_combined_file = "Data/NFL_Combined_2010_2015.csv"

# Read Data File and store into Pandas data frame
nfl_combined_df = pd.read_csv(nfl_combined_file)
nfl_combined_df.head()

,Rk,Year,Player,Pos,AV,School,College,HE,Height,Wt,40YD,Vertical,BenchReps,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr)
0,1.0,2012.0,Trevin Wade,DB,5.0,Arizona,College Stats,10-May,5'10,192.0,4.52,34.5,18.0,116.0,6.87,4.0,Cleveland Browns / 7th / 245th pick / 2012
1,2.0,2012.0,Ryan Steed,DB,0.0,Furman,NaN,10-May,5'10,195.0,4.64,34.0,12.0,121.0,6.94,4.22,NaN
2,3.0,2012.0,Coty Sensabaugh,DB,21.0,Clemson,College Stats,11-May,5'11,189.0,4.33,37.0,15.0,122.0,6.6,4.06,Tennessee Titans / 4th / 115th pick / 2012
3,4.0,2012.0,Josh Robinson,DB,12.0,Central Florida,College Stats,10-May,5'10,199.0,4.29,38.5,17.0,133.0,6.55,3.97,Minnesota Vikings / 3rd / 66th pick / 2012
4,5.0,2012.0,Shaun Prater,DB,2.0,Iowa,College Stats,10-May,5'10,190.0,4.5,NaN,14.0,NaN,NaN,NaN,Cincinnati Bengals / 5th / 156th pick / 2012

In [6]:
pro_bowl_file = "Data/Pro_Bowl_2011_2018.csv"

# Read Data File and store into Pandas data frame
pro_bowl_df = pd.read_csv(pro_bowl_file)
pro_bowl_df.head()

,Pos,Player,Conf,Tm,Age,Yrs,G,GS,Cmp,Att,...,Att.1,Yds.1,TD.1,Rec,Yds.2,TD.2,Solo,Sk,Int.1,All-pro teams
0,QB,Aaron Rodgers,NFC,GNB,28,6,15,15,343,502,...,60,257,3,0,0,0,1,0.0,0,"AP: 1st Tm, FW: 1st Tm, PFF: 1st Tm, SN: 1st Tm"
1,QB,Drew Brees,NFC,NOR,32,10,16,16,468,657,...,21,86,1,0,0,0,2,0.0,0,"AP: 2nd Tm, PFF: 2nd Tm"
2,QB,Cam Newton,NFC,CAR,22,Rook,16,16,310,517,...,126,706,14,1,27,0,1,0.0,0,NaN
3,QB,Andy Dalton,AFC,CIN,24,Rook,16,16,300,516,...,37,152,1,0,0,0,2,0.0,0,NaN
4,QB,Tom Brady,AFC,NWE,34,11,16,16,401,611,...,43,109,3,0,0,0,0,0.0,0,NaN